kind: Deployment
apiVersion: apps/v1
metadata:
  name: banking-portal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-portal-api
  template:
    metadata:
      labels:
        app: banking-portal-api
    spec:
      containers:
        - name: banking-portal-api
          image: java-springboot-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: banking-portal-api
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: java-springboot-app
